<?php

namespace app\index\controller;

use app\common\model\AdminMenu;
use app\common\model\About;
use app\common\model\Link;
use app\common\model\ParentMenu;
use app\common\model\SecondMenu;
use app\common\model\Webconfig;
use app\common\model\Contact;
use think\Controller;
use think\Db;

class Base extends Controller
{
    protected $menu;
    protected $secode_menu;
    protected $parent_menu;
    protected $about;
    protected $config;
    protected $second_controller = ['Recruitment', 'Advisorycenter', 'Feedback', 'Hot', 'Notice', 'Authority'];
    protected $config_params;
    public function _initialize()
    {
        $this->menu = new AdminMenu();
        $this->secode_menu = new SecondMenu();
        $this->parent_menu = new ParentMenu();
        $this->about = new About();
        $this->config = new Webconfig();
        $this->init();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        $where['pid'] = 52;
        $where['is_top'] = 1;
        $where['type'] = 2;
        //一级菜单
        $menu_list = $this->menu->where($where)->order('orders ASC')->select();
        $module = $this->request->module();
        $controller = $this->request->controller();
        if ($controller == 'Index') {
            $logo = $this->about->where(['source' => 'Banner'])->find();
            $logo['thumb'] = strHandleImg($logo['thumb']);;
            $this->assign('logo', $logo);
        }
        //添加url
        foreach ($menu_list as $key => $value) {
            if (empty($value['parameter'])) {
                $url = $module . '/' . $value['controller'] . '/' . $value['function'];
            }
            $menu_list[$key]['url'] = $url;
        }
        $con = lcfirst($controller);
        $c = array_filter($menu_list, function ($t) use ($con) {
            return $t['controller'] == $con;
        });
        $arr = arrForm($c);
        //二级菜单
        $second_menu = $this->menu->where(['pid' => $arr['id'], 'is_top' => 1])->order('orders DESC')->select();
        foreach ($second_menu as $key => $value) {
            if (!empty($value['controller'])) {
                if (in_array($value['controller'], $this->second_controller) || $value['controller'] != lcfirst($controller)) {
                    $url = $module . '/' . lcfirst($controller) . '/' . $value['controller'];
                } else {
                    $url = $module . '/' . lcfirst($controller) . '/' . $value['function'];
                }
            }
            $second_menu[$key]['url'] = $url;
        }
        $this->assign('second_menu', $second_menu);
        //头部logo
        $header_logo = $this->menu->where(['controller' => $controller, 'type' => 2, 'pid' => 52])->find();
        $header_logo['thumb'] = strHandleImg($header_logo['thumb']);
        $this->assign('header_logo', $header_logo);
        //获取全局配置参数
        $this->config_params = $this->config->where('web','web')->find();
        $this->assign('keywords', $this->config_params['keywords']);
        $this->assign('description', $this->config_params['desc']);
        if($controller == 'Index'){
            $title = $this->config_params['name'];
        }else{
            if($header_logo['keywords']){
                $keywords =  $header_logo['keywords'];
                $this->assign('keywords',$keywords);
            }
            if($header_logo['des']){
                $description =  $header_logo['des'];
                $this->assign('description',$description);
            }
            $title = $header_logo['name'] .'-'. $this->config_params['name'];
        }
        $this->assign('title',$title);
        $this->config_params['contact_information'] = json_decode($this->config_params['contact_information'], true);
        $thumb = $this->menu->where('id', 178)->field('thumb')->find();
        $mock_thumb = $this->menu->where('id', 181)->field('thumb')->find();
        $thumb['thumb'] = strHandleImg($thumb['thumb']);
        $mock_thumb['thumb'] = strHandleImg($mock_thumb['thumb']);
        $this->assign('thumb', $thumb);
        $this->assign('mock_thumb', $mock_thumb);
        //分公司信息
        $contact = new Contact();
        $contact_list = $contact->select();
        //学历提升的优势(共用)
        $education_list = $this->about->where(['source' => 'Enhancement'])->select();
        //查米优势(共用)
        $chami_advantage = $this->about->where('source', 'Cadult')->select();
        //底部菜单
        $condition['pid'] = 52;
        $condition['is_bot'] = 1;
        $condition['type'] = 2;
        //一级菜单底部
        $bot_menu_list = $this->menu->where($condition)->select();
        if (!empty($bot_menu_list)) {
            foreach ($bot_menu_list as $k => $v) {
                $menu = $this->menu->where(['pid' => $v['id'], 'is_bot' => 1])->select();
                $bot_menu_list[$k]['menu'] = $menu;
            }
        }
        //友情链接
        $link = new Link();
        $link_list = $link->order(['is_top'=>'desc','create_time'=>'desc'])->select();
        $this->assign('bot_menu_list', $bot_menu_list);
        $this->assign('link_list', $link_list);
        $this->assign('contact_list', $contact_list);
        $this->assign('controller', lcfirst($controller));
        $this->assign('chami_advantage', $chami_advantage);
        $this->assign('education_list', $education_list);
        $this->assign('config', $this->config_params);
        $this->assign('menus', $menu_list);
    }
}