<?php

namespace app\admin\controller;

use app\common\model\News;
use think\Session;
use think\Db;

/**
 * 权威发布
 * Class Notice
 * @package app\admin\controller
 */
class Authority extends Permissions
{
    use \app\admin\traits\Curd;
    public function _initialize()
    {
        $this->model= new News();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }
}