<?php

namespace app\admin\controller;
use app\common\model\About as Model;
use think\Db;
use think\Request;
/**
 * 成人高考天府英才优势
 * Class Cadult
 * @package app\admin\controller
 */
class Cadult extends Permissions
{
    use \app\admin\traits\Curd;
    public function _initialize()
    {
        $this->model = new Model();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }
}