<?php

namespace app\admin\controller;
use app\common\model\Contact as contactMsg;
use think\Db;
class Contact extends Permissions
{
    use \app\admin\traits\Curd;
    public function _initialize()
    {
        $this->model = new contactMsg();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        $model = new contactMsg();

        $post = $this->request->param();
        if (isset($post['keywords']) and !empty($post['keywords'])) {
            $where['phone'] = ['like', '%' . $post['keywords'] . '%'];
        }

        $message = empty($where) ? $model->order('create_time desc')->paginate(20) : $model->where($where)->order('create_time desc')->paginate(20, false, ['query' => $this->request->param()]);
        $this->assign('message', $message);
        return $this->fetch('',[
            'message'=>$message,
            'phone'=>empty($post['keywords'])? '':$post['keywords']
        ]);
    }
    public function publish()
    {
        //获取菜单id
        $id = $this->request->has('id') ? $this->request->param('id', 0, 'intval') : 0;
        //是正常添加操作
        if($id > 0) {
            //是修改操作
            if($this->request->isPost()) {
                //是提交操作
                $post = $this->request->post();
                //验证  唯一规则： 表名，字段名，排除主键值，主键名
                $validate = new \think\Validate([
                    ['company', 'require', '公司名称不能为空'],
                    ['address', 'require', '公司地址不能为空'],
                ]);
                //验证部分数据合法性
                if (!$validate->check($post)) {
                    $this->error('提交失败：' . $validate->getError());
                }
                //验证菜单是否存在
                $article = $this->model->where('id',$id)->find();
                if(empty($article)) {
                    return $this->error('id不正确');
                }
                if(false == $this->model->allowField(true)->save($post,['id'=>$id])) {
                    return $this->error('修改失败');
                } else {
                    addlog($this->model->id);//写入日志
                    return $this->success('修改成功','admin/contact/index');
                }
            } else {
                //非提交操作
                $info = $this->model->where('id',$id)->find();
                if(!empty($info)) {
                    $this->assign('info',$info);
                    return $this->fetch();
                } else {
                    return $this->error('id不正确');
                }
            }
        } else {
            //是新增操作
            if($this->request->isPost()) {
                //是提交操作
                $post = $this->request->post();
                //验证  唯一规则： 表名，字段名，排除主键值，主键名
                $validate = new \think\Validate([
                    ['company', 'require', '公司名称不能为空'],
                    ['address', 'require', '公司地址不能为空'],
                ]);
                //验证部分数据合法性
                if (!$validate->check($post)) {
                    $this->error('提交失败：' . $validate->getError());
                }
                if(false == $this->model->allowField(true)->save($post)) {
                    return $this->error('添加失败');
                } else {
                    addlog($this->model->id);//写入日志
                    return $this->success('添加成功','admin/contact/index');
                }
            } else {
                return $this->fetch();
            }
        }
    }



    //删除
    public function delete()
    {
        if($this->request->isAjax()) {
            $id = $this->request->has('id') ? $this->request->param('id', 0, 'intval') : 0;
            if(false == Db::name('contact')->where('id',$id)->delete()) {
                return $this->error('删除失败');
            } else {
                addlog($id);//写入日志
                return $this->success('删除成功');
            }
        }
    }
}