<?php

namespace app\admin\controller;

use \app\common\model\Recruitment as Model;
use think\Db;

/**
 * 人才招聘
 * Class Recruitment
 * @package app\admin\controller
 */
class Recruitment extends Permissions
{
    use \app\admin\traits\Curd;

    public function _initialize()
    {
        $this->model = new Model();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $post = $this->request->param();
        if (isset($post['keywords']) and !empty($post['keywords'])) {
            $where['phone'] = ['like', '%' . $post['keywords'] . '%'];
        }
        $info = empty($where) ? $this->model->order('create_time desc')->paginate(20) : $this->model->where($where)->order('create_time desc')->paginate(20, false, ['query' => $this->request->param()]);
        $this->assign('info', $info);
        return $this->fetch('',[
            'info'=>$info,
        ]);
    }

    public function publish()
    {
        //获取菜单id
        $id = $this->request->has('id') ? $this->request->param('id', 0, 'intval') : 0;
        //是正常添加操作
        if($id > 0) {
            //是修改操作
            if($this->request->isPost()) {
                //是提交操作
                $post = $this->request->post();
                //验证  唯一规则： 表名，字段名，排除主键值，主键名
                $validate = new \think\Validate([
                    ['position_name', 'require', '岗位名称不能为空'],
                    ['ccont', 'require', '内容不能为空'],
                ]);
                //验证部分数据合法性
                if (!$validate->check($post)) {
                    $this->error('提交失败：' . $validate->getError());
                }
                //验证菜单是否存在
                $cont = $this->model->where('id',$id)->find();
                if(empty($cont)) {
                    return $this->error('id不正确');
                }
                if(false == $this->model->allowField(true)->save($post,['id'=>$id])) {
                    return $this->error('修改失败');
                } else {
                    addlog($this->model->id);//写入日志
                    return $this->success('修改成功','admin/recruitment/index');
                }
            } else {
                //非提交操作
                $info = $this->model->where('id',$id)->find();
                if(!empty($info)) {
                    $this->assign('info',$info);
                    return $this->fetch();
                } else {
                    return $this->error('id不正确');
                }
            }
        } else {
            //是新增操作
            if($this->request->isPost()) {
                //是提交操作
                $post = $this->request->post();
                //验证  唯一规则： 表名，字段名，排除主键值，主键名
                $validate = new \think\Validate([
                    ['position_name', 'require', '岗位名称不能为空'],
                    ['ccont', 'require', '内容不能为空'],
                ]);
                //验证部分数据合法性
                if (!$validate->check($post)) {
                    $this->error('提交失败：' . $validate->getError());
                }
                if(false == $this->model->allowField(true)->save($post)) {
                    return $this->error('添加失败');
                } else {
                    addlog($this->model->id);//写入日志
                    return $this->success('添加成功','admin/recruitment/index');
                }
            } else {
                return $this->fetch();
            }
        }
    }

    //删除
    public function delete()
    {
        if($this->request->isAjax()) {
            $id = $this->request->has('id') ? $this->request->param('id', 0, 'intval') : 0;
            if(false == $this->model->where('id',$id)->delete()) {
                return $this->error('删除失败');
            } else {
                addlog($id);//写入日志
                return $this->success('删除成功');
            }
        }
    }



}